<!DOCTYPE html>
<html>
<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="generator" content="Mobirise AI v0.01, ai.mobirise.com">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
  <link rel="shortcut icon" href="assets/images/logo5.png" type="image/x-icon">
  <meta name="description" content="Сайт для отслеживания багов в программах. Отслеживайте и устраняйте ошибки в ваших программах с легкостью.">

  <title>Отслеживание Багов</title>
  <link rel="stylesheet" href="assets/web/assets/mobirise-icons2/mobirise2.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-grid.min.css">
  <link rel="stylesheet" href="assets/bootstrap/css/bootstrap-reboot.min.css">
  <link rel="stylesheet" href="assets/dropdown/css/style.css">
  <link rel="stylesheet" href="assets/socicon/css/styles.css">
  <link rel="stylesheet" href="assets/animatecss/animate.css">
  <link rel="stylesheet" href="assets/theme/css/style.css">
  <link rel="preload" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&display=swap" as="style" onload="this.onload=null;this.rel='stylesheet'">
  <noscript><link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Inter+Tight:wght@400;700&display=swap"></noscript>
  <link rel="preload" as="style" href="assets/mobirise/css/additional.css"><link rel="stylesheet" href="assets/mobirise/css/additional.css" type="text/css">



  <style>:root{ --background: #FFFAEB; --dominant-color: #FFCA3A; --primary-color: #1982C4; --secondary-color: #6A4C93; --success-color: #20AC6B; --danger-color: #AE1E2C; --warning-color: #CC9900; --info-color: #0AA3C2; --background-text: #000000; --dominant-text: #000000; --primary-text: #FFFFFF; --secondary-text: #FFFFFF; --success-text: #FFFFFF; --danger-text: #FFFFFF; --warning-text: #000000; --info-text: #FFFFFF;}</style>
</head>
<body>


    <style>
.cid-tXzkmGWAf8  {
  z-index: 1000;
  width: 100%;
  position: relative;
}
.cid-tXzkmGWAf8  .dropdown-item:before {
  font-family: Moririse2 !important;
  content: "\e966";
  display: inline-block;
  width: 0;
  position: absolute;
  left: 1rem;
  top: 0.5rem;
  margin-right: 0.5rem;
  line-height: 1;
  font-size: inherit;
  vertical-align: middle;
  text-align: center;
  overflow: hidden;
  transform: scale(0, 1);
  transition: all 0.25s ease-in-out;
}
@media (max-width: 767px) {
  .cid-tXzkmGWAf8  .navbar-toggler {
    transform: scale(0.8);
  }
}
.cid-tXzkmGWAf8  .navbar-brand {
  flex-shrink: 0;
  align-items: center;
  margin-right: 0;
  padding: 10px 0;
  transition: all 0.3s;
  word-break: break-word;
  z-index: 1;
}
.cid-tXzkmGWAf8  .navbar-brand img {
  max-width: 100%;
  max-height: 100%;
}
.cid-tXzkmGWAf8  .navbar-brand .navbar-caption {
  line-height: inherit !important;
}
.cid-tXzkmGWAf8  .navbar-brand .navbar-logo a {
  outline: none;
}
.cid-tXzkmGWAf8  .navbar-nav {
  margin: auto;
  margin-left: 0;
  margin-left: auto;
}
.cid-tXzkmGWAf8  .navbar-nav .nav-item {
  padding: 0 !important;
  transition: 0.3s all !important;
}
.cid-tXzkmGWAf8  .navbar-nav .nav-item .nav-link {
  padding: 16px !important;
  margin: 0 !important;
  border-radius: 1rem !important;
  transition: 0.3s all !important;
}
.cid-tXzkmGWAf8  .navbar-nav .nav-item .nav-link:hover {
  background-color: rgba(27, 31, 10, 0.06);
}
.cid-tXzkmGWAf8  .navbar-nav .open .nav-link::after {
  transform: rotate(180deg);
}
@media (min-width: 992px) {
  .cid-tXzkmGWAf8  .navbar-nav .open .nav-link::before {
    content: "";
    width: 100%;
    height: 20px;
    top: 100%;
    background: transparent;
    position: absolute;
  }
}
.cid-tXzkmGWAf8  .navbar-nav .dropdown-item {
  padding: 12px !important;
  border-radius: 0.5rem !important;
  margin: 0 8px !important;
  transition: 0.3s all !important;
}
.cid-tXzkmGWAf8  .navbar-nav .dropdown-item:hover {
  background-color: rgba(27, 31, 10, 0.06);
}
@media (min-width: 992px) {
  .cid-tXzkmGWAf8  .navbar-nav {
    padding-left: 1.5rem;
  }
}
.cid-tXzkmGWAf8  .nav-link {
  width: fit-content;
  position: relative;
}
.cid-tXzkmGWAf8  .navbar-logo {
  padding-left: 2rem;
  margin: 0 !important;
}
@media (max-width: 767px) {
  .cid-tXzkmGWAf8  .navbar-logo {
    padding-left: 1rem;
  }
}
.cid-tXzkmGWAf8  .navbar-caption {
  padding-left: 1rem;
  padding-right: 0.5rem;
}
@media (max-width: 767px) {
  .cid-tXzkmGWAf8  .nav-dropdown {
    padding-bottom: 0.5rem;
  }
}
.cid-tXzkmGWAf8  .nav-dropdown .link.dropdown-toggle::after {
  margin-left: 0.5rem;
  margin-top: 0.2rem;
  transition: 0.3s all;
}
.cid-tXzkmGWAf8  .container {
  display: flex;
  height: 90px;
  padding: 0.5rem 0.6rem;
  flex-wrap: nowrap;
  background: rgba(255, 255, 255, 0.8) !important;
  left: 0;
  right: 0;
  -webkit-box-pack: justify;
  -ms-flex-pack: justify;
  justify-content: flex-end;
  -webkit-box-align: center;
  -webkit-align-items: center;
  -ms-flex-align: center;
  align-items: center;
  border-radius: 100vw;
  margin-top: 1rem;
  background-color: #ffffff;
  box-shadow: 0 30px 60px 0 rgba(27, 31, 10, 0.08);
}
@media (max-width: 992px) {
  .cid-tXzkmGWAf8  .container {
    padding-right: 2rem;
  }
}
@media (max-width: 767px) {
  .cid-tXzkmGWAf8  .container {
    width: 95%;
    height: 56px !important;
    padding-right: 1rem;
    margin-top: 0rem;
  }
}
.cid-tXzkmGWAf8  .iconfont-wrapper {
  color: #000000 !important;
  font-size: 1.5rem;
  padding-right: 0.5rem;
}
.cid-tXzkmGWAf8  .dropdown-menu {
  flex-wrap: wrap;
  flex-direction: column;
  max-width: 100%;
  padding: 12px 4px !important;
  border-radius: 1.5rem;
  transition: 0.3s all !important;
  min-width: auto;
  background: #ffffff;
  background: rgba(255, 255, 255, 0.8) !important;
}
.cid-tXzkmGWAf8  .nav-item:focus,
.cid-tXzkmGWAf8  .nav-link:focus {
  outline: none;
}
.cid-tXzkmGWAf8  .dropdown .dropdown-menu .dropdown-item {
  width: auto;
  transition: all 0.25s ease-in-out;
}
.cid-tXzkmGWAf8  .dropdown .dropdown-menu .dropdown-item::after {
  right: 0.5rem;
}
.cid-tXzkmGWAf8  .dropdown .dropdown-menu .dropdown-item .mbr-iconfont {
  margin-right: 0.5rem;
  vertical-align: sub;
}
.cid-tXzkmGWAf8  .dropdown .dropdown-menu .dropdown-item .mbr-iconfont:before {
  display: inline-block;
  transform: scale(1, 1);
  transition: all 0.25s ease-in-out;
}
.cid-tXzkmGWAf8  .collapsed .dropdown-menu .dropdown-item:before {
  display: none;
}
.cid-tXzkmGWAf8  .collapsed .dropdown .dropdown-menu .dropdown-item {
  padding: 0.235em 1.5em 0.235em 1.5em !important;
  transition: none;
  margin: 0 !important;
}
.cid-tXzkmGWAf8  .navbar {
  min-height: 90px;
  transition: all 0.3s;
  border-bottom: 1px solid transparent;
  background: transparent !important;
  padding: 0 !important;
  border: none !important;
  box-shadow: none !important;
  border-radius: 0 !important;
}
.cid-tXzkmGWAf8  .navbar.opened {
  transition: all 0.3s;
}
.cid-tXzkmGWAf8  .navbar .dropdown-item {
  padding: 0.5rem 1.8rem;
}
.cid-tXzkmGWAf8  .navbar .navbar-logo img {
  width: auto;
}
.cid-tXzkmGWAf8  .navbar .navbar-collapse {
  z-index: 1;
  justify-content: flex-end;
}
.cid-tXzkmGWAf8  .navbar.collapsed {
  justify-content: center;
}
.cid-tXzkmGWAf8  .navbar.collapsed .nav-item .nav-link::before {
  display: none;
}
.cid-tXzkmGWAf8  .navbar.collapsed.opened .dropdown-menu {
  top: 0;
}
@media (min-width: 992px) {
  .cid-tXzkmGWAf8  .navbar.collapsed.opened:not(.navbar-short) .navbar-collapse {
    max-height: calc(98.5vh - 3rem);
  }
}
.cid-tXzkmGWAf8  .navbar.collapsed .dropdown-menu .dropdown-submenu {
  left: 0 !important;
}
.cid-tXzkmGWAf8  .navbar.collapsed .dropdown-menu .dropdown-item:after {
  right: auto;
}
.cid-tXzkmGWAf8  .navbar.collapsed .dropdown-menu .dropdown-toggle[data-toggle="dropdown-submenu"]:after {
  margin-left: 0.5rem;
  margin-top: 0.2rem;
  border-top: 0.35em solid;
  border-right: 0.35em solid transparent;
  border-left: 0.35em solid transparent;
  border-bottom: 0;
  top: 41%;
}
.cid-tXzkmGWAf8  .navbar.collapsed ul.navbar-nav li {
  margin: auto;
}
.cid-tXzkmGWAf8  .navbar.collapsed .dropdown-menu .dropdown-item {
  padding: 0.25rem 1.5rem;
  text-align: center;
}
.cid-tXzkmGWAf8  .navbar.collapsed .icons-menu {
  padding-left: 0;
  padding-right: 0;
  padding-top: 0.5rem;
  padding-bottom: 0.5rem;
}
@media (max-width: 767px) {
  .cid-tXzkmGWAf8  .navbar {
    min-height: 72px;
  }
  .cid-tXzkmGWAf8  .navbar .navbar-logo img {
    height: 2rem !important;
  }
}
@media (max-width: 991px) {
  .cid-tXzkmGWAf8  .navbar .nav-item .nav-link::before {
    display: none;
  }
  .cid-tXzkmGWAf8  .navbar.opened .dropdown-menu {
    top: 0;
  }
  .cid-tXzkmGWAf8  .navbar .dropdown-menu .dropdown-submenu {
    left: 0 !important;
  }
  .cid-tXzkmGWAf8  .navbar .dropdown-menu .dropdown-item:after {
    right: auto;
  }
  .cid-tXzkmGWAf8  .navbar .dropdown-menu .dropdown-toggle[data-toggle="dropdown-submenu"]:after {
    margin-left: 0.5rem;
    margin-top: 0.2rem;
    border-top: 0.35em solid;
    border-right: 0.35em solid transparent;
    border-left: 0.35em solid transparent;
    border-bottom: 0;
    top: 40%;
  }
  .cid-tXzkmGWAf8  .navbar .dropdown-menu .dropdown-item {
    padding: 0.25rem 1.5rem !important;
    text-align: center;
  }
  .cid-tXzkmGWAf8  .navbar .navbar-brand {
    flex-shrink: initial;
    flex-basis: auto;
    word-break: break-word;
    padding-right: 10px;
  }
  .cid-tXzkmGWAf8  .navbar .navbar-toggler {
    flex-basis: auto;
  }
  .cid-tXzkmGWAf8  .navbar .icons-menu {
    padding-left: 0;
    padding-top: 0.5rem;
    padding-bottom: 0.5rem;
  }
}
.cid-tXzkmGWAf8  .navbar.navbar-short .navbar-logo img {
  height: 2rem;
}
.cid-tXzkmGWAf8  .dropdown-item.active,
.cid-tXzkmGWAf8  .dropdown-item:active {
  background-color: transparent;
}
.cid-tXzkmGWAf8  .navbar-expand-lg .navbar-nav .nav-link {
  padding: 0;
}
.cid-tXzkmGWAf8  .nav-dropdown .link.dropdown-toggle {
  margin-right: 1.667em;
}
.cid-tXzkmGWAf8  .nav-dropdown .link.dropdown-toggle[aria-expanded="true"] {
  margin-right: 0;
  padding: 0.667em 1.667em;
}
.cid-tXzkmGWAf8  .navbar.navbar-expand-lg .dropdown .dropdown-menu {
  background: #ffffff;
}
.cid-tXzkmGWAf8  .navbar.navbar-expand-lg .dropdown .dropdown-menu .dropdown-submenu {
  margin: 0;
  left: 105%;
  transform: none;
  top: -12px;
}
.cid-tXzkmGWAf8  .navbar .dropdown.open > .dropdown-menu {
  display: flex;
}
.cid-tXzkmGWAf8  ul.navbar-nav {
  flex-wrap: wrap;
}
.cid-tXzkmGWAf8  .navbar-buttons {
  text-align: center;
  min-width: 140px;
}
@media (max-width: 992px) {
  .cid-tXzkmGWAf8  .navbar-buttons {
    text-align: left;
  }
}
.cid-tXzkmGWAf8  button.navbar-toggler {
  outline: none;
  width: 31px;
  height: 20px;
  cursor: pointer;
  transition: all 0.2s;
  position: relative;
  align-self: center;
}
.cid-tXzkmGWAf8  button.navbar-toggler .hamburger span {
  position: absolute;
  right: 0;
  width: 30px;
  height: 2px;
  border-right: 5px;
  background-color: #000000;
}
.cid-tXzkmGWAf8  button.navbar-toggler .hamburger span:nth-child(1) {
  top: 0;
  transition: all 0.2s;
}
.cid-tXzkmGWAf8  button.navbar-toggler .hamburger span:nth-child(2) {
  top: 8px;
  transition: all 0.15s;
}
.cid-tXzkmGWAf8  button.navbar-toggler .hamburger span:nth-child(3) {
  top: 8px;
  transition: all 0.15s;
}
.cid-tXzkmGWAf8  button.navbar-toggler .hamburger span:nth-child(4) {
  top: 16px;
  transition: all 0.2s;
}
.cid-tXzkmGWAf8  nav.opened .hamburger span:nth-child(1) {
  top: 8px;
  width: 0;
  opacity: 0;
  right: 50%;
  transition: all 0.2s;
}
.cid-tXzkmGWAf8  nav.opened .hamburger span:nth-child(2) {
  transform: rotate(45deg);
  transition: all 0.25s;
}
.cid-tXzkmGWAf8  nav.opened .hamburger span:nth-child(3) {
  transform: rotate(-45deg);
  transition: all 0.25s;
}
.cid-tXzkmGWAf8  nav.opened .hamburger span:nth-child(4) {
  top: 8px;
  width: 0;
  opacity: 0;
  right: 50%;
  transition: all 0.2s;
}
.cid-tXzkmGWAf8  .navbar-dropdown {
  padding: 0 1rem;
}
.cid-tXzkmGWAf8  a.nav-link {
  display: flex;
  align-items: center;
  justify-content: center;
}
.cid-tXzkmGWAf8  .icons-menu {
  flex-wrap: nowrap;
  display: flex;
  justify-content: center;
  padding-left: 1rem;
  padding-right: 1rem;
  padding-top: 0.3rem;
  text-align: center;
}
@media (max-width: 992px) {
  .cid-tXzkmGWAf8  .icons-menu {
    justify-content: flex-start;
    margin-bottom: 0.5rem;
  }
}
@media screen and (-ms-high-contrast: active), (-ms-high-contrast: none) {
  .cid-tXzkmGWAf8  .navbar {
    height: 70px;
  }
  .cid-tXzkmGWAf8  .navbar.opened {
    height: auto;
  }
  .cid-tXzkmGWAf8  .nav-item .nav-link:hover::before {
    width: 175%;
    max-width: calc(100% + 2rem);
    left: -1rem;
  }
}
.cid-tXzkmGWAf8  .navbar .dropdown > .dropdown-menu {
  display: none;
  width: max-content;
  max-width: 500px !important;
  transform: translateX(-50%);
  top: calc(100% + 20px);
  left: 50%;
}
.cid-tXzkmGWAf8  .navbar .dropdown > .dropdown-menu .dropdown-item {
  line-height: 1 !important;
}
.cid-tXzkmGWAf8  .navbar .dropdown > .dropdown-menu .dropdown .dropdown-item {
  align-items: center;
  display: flex;
  height: max-content !important;
  min-height: max-content !important;
}
.cid-tXzkmGWAf8  .navbar .dropdown > .dropdown-menu .dropdown .dropdown-item::after {
  display: inline-block;
  position: static;
  margin-left: 0.5rem;
  margin-top: 0;
  margin-right: 0;
  margin-bottom: 0;
  transition: 0.3s all;
  transform: rotate(-90deg);
}
.cid-tXzkmGWAf8  .navbar .dropdown > .dropdown-menu .dropdown.open .dropdown-item::after {
  transform: rotate(0deg);
}
.cid-tXzkmGWAf8  .mbr-section-btn {
  margin: -0.6rem -0.6rem;
}
.cid-tXzkmGWAf8  .navbar-toggler {
  margin-left: 12px;
  margin-right: 8px;
  order: 1000;
}
@media (max-width: 991px) {
  .cid-tXzkmGWAf8  .navbar-brand {
    margin-right: auto;
  }
  .cid-tXzkmGWAf8  .navbar-collapse {
    z-index: -1 !important;
    position: absolute;
    top: 110%;
    left: 0;
    width: 100%;
    padding: 1rem;
    border-radius: 1.5rem;
    background: #ffffff;
    opacity: 1;
    border-color: rgba(255, 255, 255, 0.8) !important;
    background: rgba(255, 255, 255, 0.8) !important;
    backdrop-filter: blur(8px);
  }
  .cid-tXzkmGWAf8  .navbar-nav .nav-item .nav-link::after {
    margin-left: 10px;
  }
  .cid-tXzkmGWAf8  .navbar-nav .dropdown-item:hover {
    background-color: rgba(27, 31, 10, 0.06);
  }
  .cid-tXzkmGWAf8  .navbar .dropdown > .dropdown-menu {
    max-width: 100% !important;
    transform: translateX(0);
    top: 10px;
    left: 0;
    padding: 8px !important;
    border-radius: 1rem;
    background-color: rgba(27, 31, 10, 0.04) !important;
  }
  .cid-tXzkmGWAf8  .navbar .dropdown > .dropdown-menu .dropdown-item {
    padding: 8px !important;
    line-height: 1 !important;
    margin-bottom: 4px !important;
  }
  .cid-tXzkmGWAf8  .navbar .dropdown > .dropdown-menu .dropdown .dropdown-item {
    align-items: center;
    display: flex;
    height: max-content !important;
    min-height: max-content !important;
  }
  .cid-tXzkmGWAf8  .navbar .dropdown > .dropdown-menu .dropdown .dropdown-item::after {
    display: inline-block;
    position: static;
    margin-left: 0.5rem;
    margin-top: 0;
    margin-right: 0;
    margin-bottom: 0;
    transition: 0.3s all;
    transform: rotate(0deg);
  }
  .cid-tXzkmGWAf8  .navbar .dropdown > .dropdown-menu .dropdown.open .dropdown-item::after {
    transform: rotate(180deg);
  }
  .cid-tXzkmGWAf8  .navbar .dropdown > .dropdown-menu .dropdown-submenu {
    position: static;
    width: 100%;
    max-width: 100% !important;
    transform: translateX(0) !important;
    top: 0;
    left: 0;
    padding: 8px !important;
    border-radius: 1rem;
    background-color: rgba(27, 31, 10, 0.04) !important;
  }
  .cid-tXzkmGWAf8  .navbar .dropdown.open > .dropdown-menu {
    display: flex !important;
    flex-direction: column;
    align-items: flex-start;
  }
}
@media (max-width: 575px) {
  .cid-tXzkmGWAf8  .navbar-collapse {
    padding: 1rem;
  }
}
</style>

<section data-bs-version="5.1" class="menu menu2 cid-tXzkmGWAf8" once="menu" id="menu-5-tXzkmGWAf8">
  <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
    <div class="container">
      <div class="navbar-brand">
        <span class="navbar-logo">
					<a href="https://mobiri.se">
						<img src="assets/images/photo-1617157382389-771cf2691904.jpeg" style="height: 3rem;">
					</a>
				</span>
				<span class="navbar-caption-wrap">
          <a class="navbar-caption text-black display-4" href="https://mobiri.se">BUGTRAKER</a>
        </span>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-bs-toggle="collapse" data-target="#navbarSupportedContent"
        data-bs-target="#navbarSupportedContent"
        aria-controls="navbarNavAltMarkup" aria-expanded="false"
        aria-label="Toggle navigation">
        <div class="hamburger">
          <span></span>
          <span></span>
          <span></span>
          <span></span>
        </div>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
          <li class="nav-item">
            <a class="nav-link link text-black display-4" href="#">Главная</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link text-black display-4" href="/issues"
              aria-expanded="false">Задачи</a>
          </li>
          <li class="nav-item">
            <a class="nav-link link text-black display-4" href="#">Профиль</a>
          </li>
        </ul>
        <div class="navbar-buttons mbr-section-btn">
          <a class="btn btn-primary display-4" href="/issue/create">Создать задачу</a>
        </div>
      </div>
    </div>
  </nav>
</section>

    <style>
.cid-tXzkmGWdS9 {
  display: flex;
}
@media (min-width: 768px) {
  .cid-tXzkmGWdS9 {
    align-items: flex-end;
  }
  .cid-tXzkmGWdS9 .row {
    justify-content: flex-start;
  }
  .cid-tXzkmGWdS9 .content-wrap {
    padding: 1rem 3rem;
  }
}
@media (max-width: 991px) and (min-width: 768px) {
  .cid-tXzkmGWdS9 .content-wrap {
    min-width: 50%;
  }
}
@media (max-width: 767px) {
  .cid-tXzkmGWdS9 {
    -webkit-align-items: center;
    align-items: flex-end;
  }
  .cid-tXzkmGWdS9 .mbr-row {
    -webkit-justify-content: center;
    justify-content: center;
  }
  .cid-tXzkmGWdS9 .content-wrap {
    width: 100%;
  }
}
.cid-tXzkmGWdS9 .mbr-fallback-image.disabled {
  display: none;
}
.cid-tXzkmGWdS9 .mbr-fallback-image {
  display: block;
  background-size: cover;
  background-position: center center;
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
  background: #000000;
}
.cid-tXzkmGWdS9 .mbr-section-title,
.cid-tXzkmGWdS9 .mbr-section-subtitle {
  text-align: left;
  color: var(--dominant-color, #ffc091);
}
.cid-tXzkmGWdS9 .mbr-text,
.cid-tXzkmGWdS9 .mbr-section-btn {
  text-align: left;
}
</style>
<section data-bs-version="5.1" class="header18 cid-tXzkmGWdS9 mbr-fullscreen" data-bg-video="https://www.youtube.com/embed/50rG8ndeoC4?autoplay&#x3D;1&amp;loop&#x3D;1&amp;playlist&#x3D;50rG8ndeoC4&amp;t&#x3D;20&amp;mute&#x3D;1&amp;playsinline&#x3D;1&amp;controls&#x3D;0&amp;showinfo&#x3D;0&amp;autohide&#x3D;1&amp;allowfullscreen&#x3D;true&amp;mode&#x3D;transparent" id="hero-15-tXzkmGWdS9">
  <div class="mbr-overlay" style="opacity: 0.3; background-color: rgb(0, 0, 0);"></div>
  <div class="container-fluid">
    <div class="row">
      <div class="content-wrap col-12 col-md-8">
        <h1
          class="mbr-section-title mbr-fonts-style mbr-white mb-4 display-1 animate__animated animate__delay-1s animate__fadeInUp">
          <strong>BUGTRAKER</strong>
        </h1>
        <p class="mbr-fonts-style mbr-text mbr-white mb-4 display-7 animate__animated animate__delay-1s animate__fadeInUp">Отслеживайте баги в программах с легкостью и уверенностью</p>

      </div>
    </div>
  </div>
</section>
    <style>
.cid-tXzkmGWJFN {
  padding-top: 8rem;
  padding-bottom: 8rem;
  background-color: transparent;
}
.cid-tXzkmGWJFN .mbr-fallback-image.disabled {
  display: none;
}
.cid-tXzkmGWJFN .mbr-fallback-image {
  display: block;
  background-size: cover;
  background-position: center center;
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
}
.cid-tXzkmGWJFN .card-wrapper {
  overflow: hidden;
  background: #ffffff;
}
.cid-tXzkmGWJFN .text-wrapper {
  padding: 4rem 3rem;
}
@media (min-width: 768px) and (max-width: 991px) {
  .cid-tXzkmGWJFN .text-wrapper {
    padding: 2.25rem;
  }
}
@media (max-width: 767px) {
  .cid-tXzkmGWJFN .text-wrapper {
    padding: 1.5rem;
  }
}
.cid-tXzkmGWJFN .row {
  align-items: center;
  margin-right: -1rem;
  margin-left: -1rem;
}
.cid-tXzkmGWJFN .row {
  flex-direction: row-reverse;
}
.cid-tXzkmGWJFN .image-wrapper {
  padding: 0 1rem;
}
.cid-tXzkmGWJFN img,
.cid-tXzkmGWJFN .image-wrapper {
  height: 600px;
  object-fit: cover;
}
@media (max-width: 767px) {
  .cid-tXzkmGWJFN img,
  .cid-tXzkmGWJFN .image-wrapper {
    max-height: 350px;
  }
}
.cid-tXzkmGWJFN .mbr-section-title {
  color: #000000;
}
.cid-tXzkmGWJFN .mbr-text {
  color: #000000;
}
</style>
<section data-bs-version="5.1" class="article05 cid-tXzkmGWJFN" id="about-us-5-tXzkmGWJFN">
  <div class="container">
    <div class="row justify-content-center align-items-center">
      <div class="col-12">
        <div class="card-wrapper">
          <div class="row">
            <div class="col-12 col-md-12 col-lg-5 image-wrapper">
              <img class="w-100" src="assets/images/photo-1491723203629-ac87f78dc19b.jpeg" alt="">
            </div>
            <div class="col-12 col-lg col-md-12">
              <div class="text-wrapper align-left">
                <h1 class="mbr-section-title mbr-fonts-style mb-4 display-2">
                  <strong>О нас</strong>
                </h1>
                <p class="mbr-text mbr-fonts-style mb-3 display-7">Мы - команда профессионалов, преданная поиску и устранению багов в программном обеспечении.</p>
                <p class="mbr-text mbr-fonts-style mb-3 display-7">Наша миссия - обеспечить безупречную работу ваших программных продуктов.</p>
                <p class="mbr-text mbr-fonts-style display-7">Мы ценим качество и эффективность в нашей работе.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    <style>
  .cid-tXzkmGX9HL {
    padding-top: 5rem;
    padding-bottom: 5rem;
    background-color: var(--dominant-color, #260a30);
  }

  .cid-tXzkmGX9HL input {
    padding: 1.2rem 1.5rem;
    border: none !important;
    height: 100%;
  }

  .cid-tXzkmGX9HL input:hover {
    border: none !important;
  }

  .cid-tXzkmGX9HL .btn {
    height: 100%;
    margin: auto;
  }

  @media (min-width: 992px) {
    .cid-tXzkmGX9HL .text-wrapper {
      padding: 0 2rem;
    }
  }

  .cid-tXzkmGX9HL .row {
    justify-content: center;
  }

  .cid-tXzkmGX9HL .mbr-section-btn {
    display: flex;
    margin-bottom: 1.2rem;
    width: fit-content;
  }

  @media (min-width: 768px) {
    .cid-tXzkmGX9HL .mbr-section-btn {
      margin-left: initial;
    }
  }

  .cid-tXzkmGX9HL .mbr-section-btn .btn {
    width: auto;
  }

  @media (max-width: 991px) {
    .cid-tXzkmGX9HL .image-wrapper {
      margin-bottom: 2rem;
    }

    .cid-tXzkmGX9HL .content-wrapper {
      flex-direction: column-reverse;
    }
  }

  .cid-tXzkmGX9HL .justify-content-center {
    align-items: center;
  }

  .cid-tXzkmGX9HL .mbr-section-title {
    text-align: center;
    color: var(--dominant-text, #ffd7ef);
  }
</style>
<section data-bs-version="5.1" class="header2 cid-tXzkmGX9HL" id="subscription-form-1-tXzkmGX9HL">
  <div class="container">
    <div class="row content-wrapper justify-content-center">
      <div class="col-lg-8 mbr-form">
        <div class="">
          <h1 class="mbr-section-title mbr-fonts-style mb-5 display-1">
            <strong>Подпишитесь на обновления</strong>
          </h1>
        </div>
        <div class="text-wrapper align-left" data-form-type="formoid">
          <form action="https://mobirise.eu/" method="POST" class="mbr-form form-with-styler" data-form-title="Form Name"><input type="hidden" name="email" data-form-email="true" value="">
            <div class="row">
              <div hidden="hidden" data-form-alert="" class="alert alert-success col-12">Thanks for filling out the form!</div>
              <div hidden="hidden" data-form-alert-danger="" class="alert alert-danger col-12">
                Oops...! some problem!
              </div>
            </div>
            <div class="dragArea row">
              <div data-for="email" class="col-lg-6 col-md-6 col-sm-12 form-group">
                <input type="email" name="email" placeholder="test@email.com" data-form-field="email" class="form-control display-7" value="" id="email-header02-0">
              </div>
              <div class="col-auto mbr-section-btn"><button type="submit" class="w-100 w-100 w-100 w-100 w-100 w-100 btn btn-secondary display-7">Подписаться</button></div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
    <style>
  .cid-tXzkmGXmJI {
    padding-top: 5rem;
    padding-bottom: 3rem;
    background-color: #ffffff;
  }
  .cid-tXzkmGXmJI .mbr-fallback-image.disabled {
    display: none;
  }
  .cid-tXzkmGXmJI .mbr-fallback-image {
    display: block;
    background-size: cover;
    background-position: center center;
    width: 100%;
    height: 100%;
    position: absolute;
    top: 0;
  }
  .cid-tXzkmGXmJI .mbr-iconfont {
    margin: auto;
    display: inline-flex;
    font-size: 2rem;
    color: var(--primary-color, #9fe870);
    width: 40px;
    justify-content: center;
    align-items: center;
  }
  .cid-tXzkmGXmJI .card-title,
  .cid-tXzkmGXmJI .iconfont-wrapper {
    color: #000000;
  }
  .cid-tXzkmGXmJI .card-text {
    color: #000000;
  }
  .cid-tXzkmGXmJI .mbr-section-title {
    color: #000000;
  }
  .cid-tXzkmGXmJI .mbr-section-subtitle {
    color: #000000;
  }
  .cid-tXzkmGXmJI .content-head {
    max-width: 800px;
  }
</style>
<section data-bs-version="5.1" class="people02 cid-tXzkmGXmJI" id="testimonials-2-tXzkmGXmJI">
	<div class="container">
		<div class="row mb-5 justify-content-center">
			<div class="col-12 content-head">
				<h3 class="mbr-section-title mbr-fonts-style align-center mb-4 display-2">
					<strong>Отзывы</strong>
				</h3>
			</div>
		</div>
		<div class="row">
				<div class="item features-without-image col-12 col-md-6 col-lg-4 mb-5">
					<div class="item-wrapper">
						<div class="card-box align-center">
							<div class="iconfont-wrapper mb-3">
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
							</div>
							<h5 class="card-title mbr-fonts-style mb-3 display-7">Благодаря BUGTRAKER, мы смогли улучшить качество нашего продукта!</h5>
							<p class="card-text mbr-fonts-style mb-0 display-7">Иван Петров</p>
						</div>
					</div>
				</div>
				<div class="item features-without-image col-12 col-md-6 col-lg-4 mb-5">
					<div class="item-wrapper">
						<div class="card-box align-center">
							<div class="iconfont-wrapper mb-3">
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
							</div>
							<h5 class="card-title mbr-fonts-style mb-3 display-7">Надежный инструмент для поиска и устранения багов. Рекомендую!</h5>
							<p class="card-text mbr-fonts-style mb-0 display-7">Елена Сидорова</p>
						</div>
					</div>
				</div>
				<div class="item features-without-image col-12 col-md-6 col-lg-4 mb-5">
					<div class="item-wrapper">
						<div class="card-box align-center">
							<div class="iconfont-wrapper mb-3">
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
							</div>
							<h5 class="card-title mbr-fonts-style mb-3 display-7">С BUGTRAKER мы больше не боимся багов. Отличный сервис!</h5>
							<p class="card-text mbr-fonts-style mb-0 display-7">Алексей Иванов</p>
						</div>
					</div>
				</div><div class="item features-without-image col-12 col-md-6 col-lg-4 mb-5">
					<div class="item-wrapper">
						<div class="card-box align-center">
							<div class="iconfont-wrapper mb-3">
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
							</div>
							<h5 class="card-title mbr-fonts-style mb-3 display-7">Программирование стало гораздо проще благодаря BUGTRAKER.</h5>
							<p class="card-text mbr-fonts-style mb-0 display-7">Мария Козлова</p>
						</div>
					</div>
				</div><div class="item features-without-image col-12 col-md-6 col-lg-4 mb-5">
					<div class="item-wrapper">
						<div class="card-box align-center">
							<div class="iconfont-wrapper mb-3">
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
							</div>
							<h5 class="card-title mbr-fonts-style mb-3 display-7">Спасибо за отличный сервис! BUGTRAKER - лучший помощник разработчика.</h5>
							<p class="card-text mbr-fonts-style mb-0 display-7">Дмитрий Николаев</p>
						</div>
					</div>
				</div><div class="item features-without-image col-12 col-md-6 col-lg-4 mb-5">
					<div class="item-wrapper">
						<div class="card-box align-center">
							<div class="iconfont-wrapper mb-3">
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
								<span class="mbr-iconfont mobi-mbri-star mobi-mbri"></span>
							</div>
							<h5 class="card-title mbr-fonts-style mb-3 display-7">BUGTRAKER - надежный партнер в поиске и устранении багов.</h5>
							<p class="card-text mbr-fonts-style mb-0 display-7">Ольга Смирнова</p>
						</div>
					</div>
				</div>
			</div>
		<div class="row mt-0 mt-md-5">
		</div>
	</div>
</section>
    <style>
  .cid-tXzkmGXHkW {
    padding-top: 5rem;
    padding-bottom: 3rem;
    background-color: transparent;
  }

  .cid-tXzkmGXHkW img,
  .cid-tXzkmGXHkW .item-img {
    width: 100%;
    height: 100%;
    height: 300px;
    object-fit: cover;
  }

  .cid-tXzkmGXHkW .item:focus,
  .cid-tXzkmGXHkW span:focus {
    outline: none;
  }

  .cid-tXzkmGXHkW .item {
    margin-bottom: 2rem;
  }

  @media (max-width: 767px) {
    .cid-tXzkmGXHkW .item {
      margin-bottom: 1rem;
    }
  }

  .cid-tXzkmGXHkW .item-content {
    margin-top: 2rem;
    padding: 0 2.25rem 2.25rem;
    display: flex;
    flex-direction: column;
    height: 100%;
  }

  @media (min-width: 992px) and (max-width: 1200px) {
    .cid-tXzkmGXHkW .item-content {
      padding: 2rem 1.5rem;
      padding-top: 1rem;
      margin-top: 1rem;
    }
  }

  @media (max-width: 767px) {
    .cid-tXzkmGXHkW .item-content {
      padding: 2rem 1.5rem;
      padding-top: 1rem;
      margin-top: 1rem;
    }
  }

  .cid-tXzkmGXHkW .item-wrapper {
    position: relative;
    background: #ffffff;
    height: 100%;
    display: flex;
    flex-flow: column nowrap;
  }

  .cid-tXzkmGXHkW .item-wrapper .item-footer {
    margin-top: auto;
  }

  .cid-tXzkmGXHkW .mbr-section-title {
    color: #000000;
  }

  .cid-tXzkmGXHkW .item-title {
    text-align: left;
  }

  .cid-tXzkmGXHkW .item-subtitle {
    text-align: left;
  }

  .cid-tXzkmGXHkW .mbr-text,
  .cid-tXzkmGXHkW .item .mbr-section-btn {
    text-align: left;
  }

  .cid-tXzkmGXHkW .content-head {
    max-width: 800px;
  }
</style>
<section data-bs-version="5.1" class="features4 cid-tXzkmGXHkW" id="service-list-2-tXzkmGXHkW">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-12 content-head">
        <div class="mbr-section-head mb-5">
          <h4 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
            <strong>Услуги</strong>
          </h4>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="item features-image col-12 col-md-6 col-lg-4">
        <div class="item-wrapper">
          <div class="item-img">
            <img src="assets/images/photo-1615443589816-bf96d07d3852.jpeg" alt="">
          </div>
          <div class="item-content">
            <h5 class="item-title mbr-fonts-style display-5">
              <strong>Регистрация в системе</strong>
            </h5>

            <p class="mbr-text mbr-fonts-style display-7">
              Простой механизм регистрации и отслеживания личного профиля в программе
            </p>
          </div>

        </div>
      </div>
      <div class="item features-image col-12 col-md-6 col-lg-4">
        <div class="item-wrapper">
          <div class="item-img">
            <img src="assets/images/photo-1626178488686-3a957cd2b7ae.jpeg" alt="">
          </div>
          <div class="item-content">
            <h5 class="item-title mbr-fonts-style display-5">
              <strong>Создание задач для отслеживания багов</strong>
            </h5>

            <p class="mbr-text mbr-fonts-style display-7">
              Подробное описание неисправностей в вашей программе и их мониторинг другими пользователями
            </p>

          </div>
        </div>
      </div>
      <div class="item features-image col-12 col-md-6 col-lg-4">
        <div class="item-wrapper">
          <div class="item-img">
            <img src="assets/images/photo-1624211904722-c10788db74de.jpeg" alt="">
          </div>
          <div class="item-content">
            <h5 class="item-title mbr-fonts-style display-5">
              <strong>Назначение тестировщика и разработчика на задачу</strong>
            </h5>

            <p class="mbr-text mbr-fonts-style display-7">
              Теперь вы всегда знаете какие задачи в работе.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    <style>
.cid-tXzkmGXq4V {
  padding-top: 6rem;
  padding-bottom: 6rem;
  background-color: #ffffff;
}
.cid-tXzkmGXq4V .mbr-fallback-image.disabled {
  display: none;
}
.cid-tXzkmGXq4V .mbr-fallback-image {
  display: block;
  background-size: cover;
  background-position: center center;
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
}
.cid-tXzkmGXq4V .title .num {
  width: 100%;
  display: block;
}
.cid-tXzkmGXq4V .title .card-title {
  z-index: 1;
}
.cid-tXzkmGXq4V .num {
  color: var(--primary-color, #9fe870);
  text-align: center;
}
.cid-tXzkmGXq4V .item-mb {
  margin-bottom: 2rem;
}
@media (max-width: 767px) {
  .cid-tXzkmGXq4V .item-mb {
    margin-bottom: 1rem;
  }
}
@media (max-width: 767px) {
  .cid-tXzkmGXq4V * {
    text-align: center !important;
  }
  .cid-tXzkmGXq4V .content-column {
    margin-bottom: 2rem;
  }
}
.cid-tXzkmGXq4V .content-head {
  max-width: 800px;
}
.cid-tXzkmGXq4V .card-text {
  text-align: center;
}
.cid-tXzkmGXq4V .card-title,
.cid-tXzkmGXq4V .card-img {
   text-align: center;
}
</style>
<section data-bs-version="5.1" class="features023 cid-tXzkmGXq4V" id="metrics-1-tXzkmGXq4V">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 content-head">
                <div class="card-wrapper mb-5">
                    <div class="card-box align-center">
                    </div>
                </div>
            </div>
        </div>
        <div class="row content-row">
            <div class="item features-without-image col-12 col-md-6 col-lg-4 item-mb">
                <div class="item-wrapper">
                    <div class="title mb-3">
                        <span class="num mbr-fonts-style display-1"><strong>1500+</strong></span>
                    </div>
                    <h4 class="card-title mbr-fonts-style display-5">
                        <strong>довольных клиентов</strong>
                    </h4>
                </div>
            </div>
            <div class="item features-without-image col-12 col-md-6 col-lg-4 item-mb">
                <div class="item-wrapper">
                    <div class="title mb-3">
                        <span class="num mbr-fonts-style display-1"><strong>99%</strong></span>
                    </div>
                    <h4 class="card-title mbr-fonts-style display-5">
                        <strong>покрытие багов</strong>
                    </h4>
                </div>
            </div>
            <div class="item features-without-image col-12 col-md-6 col-lg-4 item-mb">
                <div class="item-wrapper">
                    <div class="title mb-3">
                        <span class="num mbr-fonts-style display-1"><strong>24/7</strong></span>
                    </div>
                    <h4 class="card-title mbr-fonts-style display-5">
                        <strong>поддержка клиентов</strong>
                    </h4>
                </div>
            </div>
        </div>
    </div>
</section>
    <style>
.cid-tXzkmGXWFs {
  padding-top: 5rem;
  padding-bottom: 5rem;
  background-color: transparent;
}
.cid-tXzkmGXWFs .mbr-text {
  color: #000000;
}
.cid-tXzkmGXWFs .mbr-section-subtitle {
  color: #000000;
}
.cid-tXzkmGXWFs .mbr-section-title {
  color: #000000;
  text-align: center;
}
.cid-tXzkmGXWFs .mbr-text,
.cid-tXzkmGXWFs .item .mbr-section-btn {
  text-align: left;
}
.cid-tXzkmGXWFs .item-wrapper {
  background: #ffffff;
  margin-bottom: 2rem;
  padding: 2.25rem;
}
@media (min-width: 992px) and (max-width: 1200px) {
  .cid-tXzkmGXWFs .item-wrapper {
    padding: 2rem 1.5rem;
    margin-bottom: 2rem;
  }
}
@media (max-width: 767px) {
  .cid-tXzkmGXWFs .item-wrapper {
    padding: 2rem 1.5rem;
    margin-bottom: 1rem;
  }
}

</style>
<section data-bs-version="5.1" class="list05 cid-tXzkmGXWFs" id="faq-2-tXzkmGXWFs">
    <div class="container">
        <div class="col-12 mb-5 content-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <strong>Часто задаваемые вопросы</strong>
            </h3>
        </div>
        <div class="row justify-content-center">
            <div class="col-12 col-lg-8">
                <div class="item features-without-image col-12 active">
                    <div class="item-wrapper">
                        <h5 class="mbr-card-title mbr-fonts-style mt-0 mb-3 display-5">
                            <strong>Как начать использовать BUGTRAKER?</strong></h5>
                        <p class="mbr-text mbr-fonts-style mt-0 mb-3 display-7">
                            Просто зарегистрируйтесь на нашем сайте и начните отслеживать баги ваших программ.
                        </p>
                    </div>
                </div>
                <div class="item features-without-image col-12">
                    <div class="item-wrapper">
                        <h5 class="mbr-card-title mbr-fonts-style mt-0 mb-3 display-5">
                            <strong>Как связаться с поддержкой?</strong></h5>
                        <p class="mbr-text mbr-fonts-style mt-0 mb-3 display-7">
                            Вы можете написать нам на почту support@bugtraker.com.
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</section>
    <style>
  .cid-tXzkmGXU3n {
    padding-top: 6rem;
    padding-bottom: 6rem;
    background: transparent;
  }
  .cid-tXzkmGXU3n .mbr-fallback-image.disabled {
    display: none;
  }
  .cid-tXzkmGXU3n .mbr-fallback-image {
    display: block;
    background-size: cover;
    background-position: center center;
    width: 100%;
    height: 100%;
    position: absolute;
    top: 0;
  }
  @media (min-width: 768px) {
    .cid-tXzkmGXU3n .container-fluid {
      padding: 0;
    }
  }
  .cid-tXzkmGXU3n .embla__slide {
    display: flex;
    justify-content: center;
    position: relative;
    min-width: 490px;
    max-width: 490px;
  }
  @media (max-width: 768px) {
    .cid-tXzkmGXU3n .embla__slide {
      min-width: 100%;
      max-width: 100%;
      margin-left: 1rem !important;
      margin-right: 1rem !important;
    }
  }
  .cid-tXzkmGXU3n .embla__slide a {
    display: block;
    width: 100%;
  }
  .cid-tXzkmGXU3n .embla__button--next,
  .cid-tXzkmGXU3n .embla__button--prev {
    display: flex;
  }
  .cid-tXzkmGXU3n .mobi-mbri-arrow-next {
    margin-left: 5px;
  }
  .cid-tXzkmGXU3n .mobi-mbri-arrow-prev {
    margin-right: 5px;
  }
  .cid-tXzkmGXU3n .embla__button {
    top: 50%;
    width: 60px;
    height: 60px;
    margin-top: -1.5rem;
    font-size: 22px;
    border: 2px solid #fff;
    border-radius: 50%;
    transition: all 0.3s;
    position: absolute;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  .cid-tXzkmGXU3n .embla__button:disabled {
    cursor: default;
    display: none;
  }
  .cid-tXzkmGXU3n .embla__button.embla__button--prev {
    left: 0;
    margin-left: 2.5rem;
  }
  .cid-tXzkmGXU3n .embla__button.embla__button--next {
    right: 0;
    margin-right: 2.5rem;
  }
  @media (max-width: 767px) {
    .cid-tXzkmGXU3n .embla__button {
      top: auto;
      bottom: 1rem;
    }
  }
  .cid-tXzkmGXU3n .embla {
    position: relative;
    width: 100%;
  }
  .cid-tXzkmGXU3n .embla__viewport {
    overflow: hidden;
    width: 100%;
  }
  .cid-tXzkmGXU3n .embla__viewport.is-draggable {
    cursor: grab;
  }
  .cid-tXzkmGXU3n .embla__viewport.is-dragging {
    cursor: grabbing;
  }
  .cid-tXzkmGXU3n .embla__slide a {
    cursor: grab;
  }
  .cid-tXzkmGXU3n .embla__slide a:active {
    cursor: grabbing;
  }
  .cid-tXzkmGXU3n .embla__container {
    display: flex;
    user-select: none;
    -webkit-touch-callout: none;
    -khtml-user-select: none;
    -webkit-tap-highlight-color: transparent;
  }
  .cid-tXzkmGXU3n .item-menu-overlay {
    border-radius: 2rem;
  }
  .cid-tXzkmGXU3n .mbr-section-title {
    color: #232323;
  }
  .cid-tXzkmGXU3n .mbr-section-subtitle {
    color: #232323;
  }
  .cid-tXzkmGXU3n .mbr-box {
    color: #ffffff;
  }
  .cid-tXzkmGXU3n .slide-content {
    position: relative;
    border-radius: 4px;
    height: 100%;
    display: flex;
    overflow: hidden;
    flex-flow: column nowrap;
  }
  .cid-tXzkmGXU3n img,
  .cid-tXzkmGXU3n .item-img {
    width: 100%;
    height: 400px;
    object-fit: cover;
  }
  .cid-tXzkmGXU3n .item-wrapper {
    position: relative;
  }
  .cid-tXzkmGXU3n .content-head {
    max-width: 800px;
  }
</style>
<section
  data-bs-version="5.1"
  class="slider4 mbr-embla cid-tXzkmGXU3n"
  id="gallery-5-tXzkmGXU3n"
>
  <div class="container-fluid">
    <div class="row mb-5 justify-content-center">
      <div class="col-12 content-head">
        <h3
          class="mbr-section-title mbr-fonts-style align-center mb-0 display-2"
        >
          <strong>Галерея</strong>
        </h3>
      </div>
    </div>
    <div class="row">
      <div class="col-12">
        <div
          class="embla position-relative"
          data-skip-snaps="true"
          data-align="center"
          data-contain-scroll="trimSnaps"
          data-loop="true"
          data-auto-play-interval="5"
          data-draggable="true"
        >
          <div class="embla__viewport">
            <div class="embla__container">
              <div
                class="embla__slide slider-image item"
                style="margin-left: 1rem; margin-right: 1rem;"
              >
                <div class="slide-content">
                  <div class="item-img">
                    <div class="item-wrapper">
                      <img
                        src="assets/images/photo-1599732020777-57e69cb66703.jpeg"
                        title=""
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div
                class="embla__slide slider-image item"
                style="margin-left: 1rem; margin-right: 1rem;"
              >
                <div class="slide-content">
                  <div class="item-img">
                    <div class="item-wrapper">
                      <img
                        src="assets/images/photo-1570623354073-69b1cfcada12.jpeg"
                        title=""
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div
                class="embla__slide slider-image item"
                style="margin-left: 1rem; margin-right: 1rem;"
              >
                <div class="slide-content">
                  <div class="item-img">
                    <div class="item-wrapper">
                      <img
                        src="assets/images/photo-1516434464077-12b1b87bb716.jpeg"
                        title=""
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div
                class="embla__slide slider-image item"
                style="margin-left: 1rem; margin-right: 1rem;"
              >
                <div class="slide-content">
                  <div class="item-img">
                    <div class="item-wrapper">
                      <img
                        src="assets/images/photo-1534198601173-4de3342a0b62.jpeg"
                        title=""
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div
                class="embla__slide slider-image item"
                style="margin-left: 1rem; margin-right: 1rem;"
              >
                <div class="slide-content">
                  <div class="item-img">
                    <div class="item-wrapper">
                      <img
                        src="assets/images/photo-1592236307620-c43889a74334.jpeg"
                        title=""
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <button class="embla__button embla__button--prev">
            <span
              class="mobi-mbri mobi-mbri-arrow-prev"
              aria-hidden="true"
            ></span>
            <span
              class="sr-only visually-hidden visually-hidden"
            >Previous</span>
          </button>
          <button class="embla__button embla__button--next">
            <span
              class="mobi-mbri mobi-mbri-arrow-next"
              aria-hidden="true"
            ></span>
            <span class="sr-only visually-hidden visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </div>
  </div>
</section>
    <style>
.cid-tXzkmGYzfH {
  padding-top: 5rem;
  padding-bottom: 5rem;
  background-color: transparent;
}
.cid-tXzkmGYzfH .mbr-fallback-image.disabled {
  display: none;
}
.cid-tXzkmGYzfH .mbr-fallback-image {
  display: block;
  background-size: cover;
  background-position: center center;
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
}
@media (max-width: 767px) {
  .cid-tXzkmGYzfH .card-content-text {
    padding: 1.5rem 1.5rem 0 1.5rem;
  }
}
@media (min-width: 768px) {
  .cid-tXzkmGYzfH .card-content-text {
    padding: 2.25rem 2.25rem 0 2.25rem;
  }
}
@media (min-width: 992px) {
  .cid-tXzkmGYzfH .card-content-text {
    padding: 4rem 4rem 1rem 4rem;
  }
}
.cid-tXzkmGYzfH .card-wrapper {
  background: #ffffff;
}
.cid-tXzkmGYzfH .mbr-text,
.cid-tXzkmGYzfH .mbr-section-btn {
  color: #000000;
  text-align: left;
}
.cid-tXzkmGYzfH .card-title,
.cid-tXzkmGYzfH .card-box {
  text-align: left;
  color: #000000;
}
</style>
<section data-bs-version="5.1" class="article9 cid-tXzkmGYzfH" id="generic-text-9-tXzkmGYzfH">
  <div class="container">
    <div class="row justify-content-center">
      <div class="card col-md-12 col-lg-10">
        <div class="card-wrapper">
          <div class="card-content-text">
            <h3 class="card-title mbr-fonts-style mbr-white mt-3 mb-4 display-2">
            <strong>Преимущества BUGTRAKER</strong>
          </h3>
          <div class="row card-box align-left">
            <div class="item features-without-image col-12">
              <div class="item-wrapper">
                <p class="mbr-text mbr-fonts-style display-7">BUGTRAKER - это надежный инструмент для отслеживания и устранения багов в вашем программном обеспечении.</p>
              </div>
            </div>
            <div class="item features-without-image col-12">
              <div class="item-wrapper">
                <p class="mbr-text mbr-fonts-style display-7">С нами вы можете быть уверены в качестве вашего продукта и удовлетворенности ваших клиентов.</p>
              </div>
            </div>
            <div class="item features-without-image col-12">
              <div class="item-wrapper">
                <p class="mbr-text mbr-fonts-style display-7">Присоединяйтесь к нам прямо сейчас и убедитесь в эффективности нашего сервиса.</p>
              </div>
            </div>
          </div>
          </div>
          <div class="image-wrapper d-flex justify-content-center mt-3">
            <img src="assets/images/photo-1619616294580-ce65bf9a9776.jpeg">
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    <style>
  .cid-tXzkmGYeY0 {
    padding-top: 5rem;
    padding-bottom: 5rem;
    background-color: transparent;
  }
  .cid-tXzkmGYeY0 img,
  .cid-tXzkmGYeY0 .item-img {
    width: 100%;
    height: 100%;
    height: 400px;
    object-fit: cover;
  }
  @media (max-width: 767px) {
    .cid-tXzkmGYeY0 img,
    .cid-tXzkmGYeY0 .item-img {
      max-height: 300px;
    }
  }
  .cid-tXzkmGYeY0 .item:focus,
  .cid-tXzkmGYeY0 span:focus {
    outline: none;
  }
  .cid-tXzkmGYeY0 .item-wrapper {
    position: relative;
  }
  .cid-tXzkmGYeY0 .slide-content {
    position: relative;
    border-radius: 4px;
    background: #ffffff;
    height: 100%;
    display: flex;
    overflow: hidden;
    flex-flow: column nowrap;
  }
  @media (min-width: 768px) {
    .cid-tXzkmGYeY0 .slide-content .item-content {
      padding: 2.25rem 2.25rem 0;
    }
    .cid-tXzkmGYeY0 .slide-content .item-footer {
      padding: 0 2.25rem 2.25rem;
    }
  }
  @media (max-width: 767px) {
    .cid-tXzkmGYeY0 .slide-content .item-content {
      padding: 1.5rem 1.5rem 0;
    }
    .cid-tXzkmGYeY0 .slide-content .item-footer {
      padding: 0 1.5rem 1.5rem;
    }
  }
  .cid-tXzkmGYeY0 .mbr-section-btn {
    margin-top: auto !important;
  }
  .cid-tXzkmGYeY0 .mbr-section-title {
    color: #000000;
  }
  .cid-tXzkmGYeY0 .mbr-text,
  .cid-tXzkmGYeY0 .mbr-section-btn {
    text-align: left;
  }
  .cid-tXzkmGYeY0 .item-title {
    text-align: left;
  }
  .cid-tXzkmGYeY0 .item-subtitle {
    text-align: left;
    color: #000000;
  }
  .cid-tXzkmGYeY0 .embla__slide {
    display: flex;
    justify-content: center;
    position: relative;
    min-width: 370px;
    max-width: 370px;
  }
  @media (max-width: 768px) {
    .cid-tXzkmGYeY0 .embla__slide {
      min-width: 85%;
      max-width: initial;
    }
  }
  .cid-tXzkmGYeY0 .embla__button--next,
  .cid-tXzkmGYeY0 .embla__button--prev {
    display: flex;
  }
  .cid-tXzkmGYeY0 .embla__button {
    top: 50%;
    width: 60px;
    height: 60px;
    margin-top: -1.5rem;
    font-size: 22px;
    background-color: rgba(0, 0, 0, 0.5);
    color: #fff;
    border: 2px solid #fff;
    border-radius: 50%;
    transition: all 0.3s;
    position: absolute;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  @media (max-width: 768px) {
    .cid-tXzkmGYeY0 .embla__button {
      display: none;
    }
  }
  .cid-tXzkmGYeY0 .embla__button:disabled {
    cursor: default;
    display: none;
  }
  .cid-tXzkmGYeY0 .embla__button:hover {
    background: #000;
    color: rgba(255, 255, 255, 0.5);
  }
  .cid-tXzkmGYeY0 .embla__button.embla__button--prev {
    left: 0;
    margin-left: 2.5rem;
  }
  .cid-tXzkmGYeY0 .embla__button.embla__button--next {
    right: 0;
    margin-right: 2.5rem;
  }
  @media (max-width: 767px) {
    .cid-tXzkmGYeY0 .embla__button {
      top: auto;
    }
  }
  .cid-tXzkmGYeY0 .embla {
    position: relative;
    width: 100%;
  }
  .cid-tXzkmGYeY0 .embla__viewport {
    overflow: hidden;
    width: 100%;
  }
  .cid-tXzkmGYeY0 .embla__viewport.is-draggable {
    cursor: grab;
  }
  .cid-tXzkmGYeY0 .embla__viewport.is-dragging {
    cursor: grabbing;
  }
  .cid-tXzkmGYeY0 .embla__container {
    display: flex;
    user-select: none;
    -webkit-touch-callout: none;
    -khtml-user-select: none;
    -webkit-tap-highlight-color: transparent;
  }
  @media (max-width: 768px) {
    .cid-tXzkmGYeY0 .embla__container .embla__slide:first-child {
      margin-left: 2rem !important;
    }
    .cid-tXzkmGYeY0 .embla__container .embla__slide:last-child {
      margin-right: 2rem !important;
    }
  }
  .cid-tXzkmGYeY0 .content-head {
    max-width: 800px;
  }
</style>
<section data-bs-version="5.1" class="features_17 mbr-embla cid-tXzkmGYeY0" id="features-17-tXzkmGYeY0">
	<div class="position-relative">
		<div class="container-fluid">
			<div class="row justify-content-center">
				<div class="col-12 content-head">
					<div class="mbr-section-head mb-5">
						<h4 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
							<strong>Преимущества BUGTRAKER</strong>
						</h4>
						<h5 class="mbr-section-subtitle mbr-fonts-style align-center mb-0 mt-4 display-7">Почему выбирают нас?</h5>
					</div>
				</div>
			</div>
		</div>
		<div class="embla" data-skip-snaps="true" data-align="center" data-contain-scroll="trimSnaps" data-auto-play-interval="5" data-draggable="true">
			<div class="embla__viewport container-fluid">
				<div class="embla__container">
					<div class="embla__slide slider-image item active" style="margin-left: 1rem; margin-right: 1rem;">
						<div class="slide-content">
							<div class="item-img">
								<div class="item-wrapper">
									<img src="assets/images/photo-1516434593931-42aaf04e6ef2.jpeg" title="" data-slide-to="1" data-bs-slide-to="1">
								</div>
							</div>
							<div class="item-content">
								<h5 class="item-title mbr-fonts-style display-5">
									<strong>Надежность</strong>
								</h5>
								<p class="mbr-text mbr-fonts-style mt-3 display-7">Мы гарантируем надежность и эффективность нашего сервиса.</p>
							</div>

						</div>
					</div>
					<div class="embla__slide slider-image item" style="margin-left: 1rem; margin-right: 1rem;">
						<div class="slide-content">
							<div class="item-img">
								<div class="item-wrapper">
									<img src="assets/images/photo-1589810406186-14d8b49de26b.jpeg" title="" data-slide-to="2" data-bs-slide-to="2">
								</div>
							</div>
							<div class="item-content">
								<h5 class="item-title mbr-fonts-style display-5">
									<strong>Эффективность</strong>
								</h5>
								<p class="mbr-text mbr-fonts-style mt-3 display-7">BUGTRAKER помогает устранить баги быстро и эффективно.</p>
							</div>

						</div>
					</div>
					<div class="embla__slide slider-image item" style="margin-left: 1rem; margin-right: 1rem;">
						<div class="slide-content">
							<div class="item-img">
								<div class="item-wrapper">
									<img src="assets/images/photo-1511954766786-1f88f53fb528.jpeg" title="" data-slide-to="3" data-bs-slide-to="3">
								</div>
							</div>
							<div class="item-content">
								<h5 class="item-title mbr-fonts-style display-5">
									<strong>Простота</strong>
								</h5>
								<p class="mbr-text mbr-fonts-style mt-3 display-7">Простой и интуитивно понятный интерфейс для всех пользователей.</p>
							</div>

						</div>
					</div>
					<div class="embla__slide slider-image item" style="margin-left: 1rem; margin-right: 1rem;">
						<div class="slide-content">
							<div class="item-img">
								<div class="item-wrapper">
									<img src="assets/images/photo-1619616294321-e33bccb598bb.jpeg" title="" data-slide-to="4" data-bs-slide-to="4">
								</div>
							</div>
							<div class="item-content">
								<h5 class="item-title mbr-fonts-style display-5">
									<strong>Поддержка</strong>
								</h5>
								<p class="mbr-text mbr-fonts-style mt-3 display-7">Мы предоставляем круглосуточную поддержку для наших клиентов.</p>
							</div>

						</div>
					</div>
					<div class="embla__slide slider-image item" style="margin-left: 1rem; margin-right: 1rem;">
						<div class="slide-content">
							<div class="item-img">
								<div class="item-wrapper">
									<img src="assets/images/photo-1584731558808-e2f61078f172.jpeg" title="" data-slide-to="5" data-bs-slide-to="5">
								</div>
							</div>
							<div class="item-content">
								<h5 class="item-title mbr-fonts-style display-5">
									<strong>Инновации</strong>
								</h5>
								<p class="mbr-text mbr-fonts-style mt-3 display-7">Мы постоянно внедряем новые технологии для улучшения нашего сервиса.</p>
							</div>

						</div>
					</div>
				</div>
			</div>
			<button class="embla__button embla__button--prev">
				<span class="mobi-mbri mobi-mbri-arrow-prev mbr-iconfont" aria-hidden="true"></span>
				<span class="sr-only visually-hidden visually-hidden visually-hidden">Previous</span>
			</button>
			<button class="embla__button embla__button--next">
				<span class="mobi-mbri mobi-mbri-arrow-next mbr-iconfont" aria-hidden="true"></span>
				<span class="sr-only visually-hidden visually-hidden visually-hidden">Next</span>
			</button>
		</div>
	</div>
</section>
    <style>
  .cid-tXzkmGZvZJ {
    padding-top: 6rem;
    padding-bottom: 6rem;
    background-color: #ffffff;
  }
  .cid-tXzkmGZvZJ .item-subtitle {
    line-height: 1.2;
    color: #000000;
  }
  .cid-tXzkmGZvZJ img,
  .cid-tXzkmGZvZJ .item-img {
    width: 100%;
    height: 100%;
    height: 400px;
    object-fit: cover;
  }
  .cid-tXzkmGZvZJ .item:focus,
  .cid-tXzkmGZvZJ span:focus {
    outline: none;
  }
  .cid-tXzkmGZvZJ .item {
    margin-bottom: 2rem;
  }
  @media (max-width: 767px) {
    .cid-tXzkmGZvZJ .item {
      margin-bottom: 1rem;
    }
  }
  .cid-tXzkmGZvZJ .item-wrapper {
    position: relative;
    border-radius: 4px;
    height: 100%;
    display: flex;
    flex-flow: column nowrap;
  }
  .cid-tXzkmGZvZJ .mbr-section-title {
    color: #232323;
  }
  .cid-tXzkmGZvZJ .mbr-text,
  .cid-tXzkmGZvZJ .mbr-section-btn {
    color: #232323;
  }
  .cid-tXzkmGZvZJ .item-title {
    color: #232323;
  }
  .cid-tXzkmGZvZJ .content-head {
    max-width: 800px;
  }
</style>
<section data-bs-version="5.1" class="features03 cid-tXzkmGZvZJ" id="events-1-tXzkmGZvZJ">
	<div class="container-fluid">
		<div class="row justify-content-center mb-5">
			<div class="col-12 content-head">
				<div class="mbr-section-head">
					<h4 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
						<strong>События</strong>
					</h4>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="item features-image col-12 col-md-6 col-lg-3 active">
				<div class="item-wrapper">
					<div class="item-img mb-3">
						<img src="assets/images/photo-1516793985388-6155f13d54ee.jpeg" title="">
					</div>
					<div class="item-content align-left">
						<h6 class="item-subtitle mbr-fonts-style mb-3 display-5">
							<strong><a class="text-black fw-bold" href="#">Вебинар по отслеживанию багов</a></strong>
						</h6>
						<p class="mbr-text mbr-fonts-style mb-3 display-7">15 декабря 2023</p>
						<p class="mbr-text mbr-fonts-style mb-3 display-7">Примите участие в нашем вебинаре и узнайте все секреты отслеживания багов.</p>

					</div>
				</div>
			</div>
			<div class="item features-image col-12 col-md-6 col-lg-3">
				<div class="item-wrapper">
					<div class="item-img mb-3">
						<img src="assets/images/photo-1454047545088-4d599ca277de.jpeg" title="" data-slide-to="1" data-bs-slide-to="1">
					</div>
					<div class="item-content align-left">
						<h6 class="item-subtitle mbr-fonts-style mb-3 display-5">
							<strong><a class="text-black fw-bold" href="#">Конференция по программированию</a></strong>
						</h6>
						<p class="mbr-text mbr-fonts-style mb-3 display-7">20 января 2024</p>
						<p class="mbr-text mbr-fonts-style mb-3 display-7">Посетите нашу конференцию и узнайте о последних тенденциях в программировании.</p>

					</div>
				</div>
			</div>
			<div class="item features-image col-12 col-md-6 col-lg-3">
				<div class="item-wrapper">
					<div class="item-img mb-3">
						<img src="assets/images/photo-1619532474053-e9de8d7d4046.jpeg" title="" data-slide-to="2" data-bs-slide-to="2">
					</div>
					<div class="item-content align-left">
						<h6 class="item-subtitle mbr-fonts-style mt-0 mb-3 display-5">
							<strong><a class="text-black fw-bold" href="#">Мастер-класс по устранению багов</a></strong>
						</h6>
						<p class="mbr-text mbr-fonts-style mb-3 display-7">10 февраля 2024</p>
						<p class="mbr-text mbr-fonts-style mb-3 display-7">Примите участие в нашем мастер-классе и научитесь эффективно устранять баги в программах.</p>

					</div>
				</div>
			</div>
			<div class="item features-image col-12 col-md-6 col-lg-3">
				<div class="item-wrapper">
					<div class="item-img mb-3">
						<img src="assets/images/photo-1622779000184-967714a46f49.jpeg" title="" data-slide-to="3" data-bs-slide-to="3">
					</div>
					<div class="item-content align-left">
						<h6 class="item-subtitle mbr-fonts-style mt-0 mb-3 display-5">
							<strong><a class="text-black fw-bold" href="#">Презентация нового функционала</a></strong>
						</h6>
						<p class="mbr-text mbr-fonts-style mb-3 display-7">5 марта 2024</p>
						<p class="mbr-text mbr-fonts-style mb-3 display-7">Узнайте первым о новом функционале в нашем сервисе на нашей презентации.</p>

					</div>
				</div>
			</div>
		</div>
	</div>
</section>
    <style>
.cid-tXzkmH0hD8 {
  padding-top: 5rem;
  padding-bottom: 5rem;
  background-color: transparent;
}
.cid-tXzkmH0hD8 .mbr-fallback-image.disabled {
  display: none;
}
.cid-tXzkmH0hD8 .mbr-fallback-image {
  display: block;
  background-size: cover;
  background-position: center center;
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
}
.cid-tXzkmH0hD8 .card-wrapper {
  background: #ffffff;
}
@media (max-width: 767px) {
  .cid-tXzkmH0hD8 .card-wrapper {
    padding: 2rem 1.5rem;
  }
}
@media (min-width: 768px) and (max-width: 991px) {
  .cid-tXzkmH0hD8 .card-wrapper {
    padding: 2.25rem;
  }
}
@media (min-width: 992px) {
  .cid-tXzkmH0hD8 .card-wrapper {
    padding: 4rem;
  }
}
.cid-tXzkmH0hD8 .mbr-text,
.cid-tXzkmH0hD8 .mbr-section-btn {
  color: #000000;
  text-align: left;
}
.cid-tXzkmH0hD8 .card-title,
.cid-tXzkmH0hD8 .card-box {
  text-align: center;
  color: #000000;
}
.cid-tXzkmH0hD8 .mbr-card-title {
  text-align: left;
}
.cid-tXzkmH0hD8 .mbr-card-subtitle {
  text-align: left;
}
.cid-tXzkmH0hD8 .mbr-text {
  text-align: left;
}
.cid-tXzkmH0hD8 .mbr-section-subtitle {
  text-align: center;
}

</style>
<section data-bs-version="5.1" class="timeline04 cid-tXzkmH0hD8" id="timeline-4-tXzkmH0hD8">
  <div class="container">
    <div class="row justify-content-center">
      <div class="card col-md-12 col-lg-10">
        <div class="card-wrapper">
          <div class="row justify-content-center">
            <div class="col-12 mb-5 content-head">
              <h3 class="card-title mbr-fonts-style mbr-white mt-3 display-2">
                <strong>История BUGTRAKER</strong>
              </h3>
            </div>
          </div>
          <div class="card-box">
            <div class="row justify-content-center item features-without-image mb-5">
              <div class="col-12 col-lg-2">
                <h5 class="mbr-card-title mbr-fonts-style mt-0 mb-3 display-7">
                  2018
                </h5>
              </div>
              <div class="col-12 col-lg-4">
                <h6 class="mbr-card-subtitle mbr-fonts-style mt-0 mb-3 display-7">
                  <strong>Начало пути</strong>
                </h6>
              </div>
              <div class="col-md-12 col-lg item-wrapper">
                <p class="mbr-text mbr-fonts-style mt-0 mb-0 display-7">
                    Мы основали BUGTRAKER с целью помочь разработчикам в поиске и устранении багов в программах.
                </p>
              </div>
            </div>
            <div class="row justify-content-center item features-without-image mb-5">
              <div class="col-12 col-lg-2">
                <h5 class="mbr-card-title mbr-fonts-style mt-0 mb-3 display-7">
                  2019
                </h5>
              </div>
              <div class="col-12 col-lg-4">
                <h6 class="mbr-card-subtitle mbr-fonts-style mt-0 mb-3 display-7">
                  <strong>Первый клиент</strong>
                </h6>
              </div>
              <div class="col-md-12 col-lg item-wrapper">
                <p class="mbr-text mbr-fonts-style mt-0 mb-0 display-7">
                  Мы получили своего первого клиента, который остается с нами и по сей день.
                </p>
              </div>
            </div>
            <div class="row justify-content-center item features-without-image mb-5">
              <div class="col-12 col-lg-2">
                <h5 class="mbr-card-title mbr-fonts-style mt-0 mb-3 display-7">
                  2020
                </h5>
              </div>
              <div class="col-12 col-lg-4">
                <h6 class="mbr-card-subtitle mbr-fonts-style mt-0 mb-3 display-7">
                  <strong>Расширение команды</strong>
                </h6>
              </div>
              <div class="col-md-12 col-lg item-wrapper">
                <p class="mbr-text mbr-fonts-style mt-0 mb-0 display-7">
                  Наша команда значительно выросла, чтобы обеспечить лучший сервис для наших клиентов.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
    <style>
  .cid-tXzkmH0g2D {
    padding-top: 5rem;
    padding-bottom: 3rem;
    background-color: #ffffff;
  }
  .cid-tXzkmH0g2D .item-subtitle {
    line-height: 1.2;
    color: #000000;
    text-align: center;
  }
  .cid-tXzkmH0g2D img,
  .cid-tXzkmH0g2D .item-img {
    width: 100%;
    height: 100%;
    height: 400px;
    object-fit: cover;
  }
  .cid-tXzkmH0g2D .item:focus,
  .cid-tXzkmH0g2D span:focus {
    outline: none;
  }
  .cid-tXzkmH0g2D .item {
    margin-bottom: 2rem;
  }
  @media (max-width: 767px) {
    .cid-tXzkmH0g2D .item {
      margin-bottom: 1rem;
    }
  }
  .cid-tXzkmH0g2D .item-wrapper {
    position: relative;
    border-radius: 4px;
    display: flex;
    flex-flow: column nowrap;
  }
  .cid-tXzkmH0g2D .mbr-section-btn {
    margin-top: auto !important;
  }
  .cid-tXzkmH0g2D .mbr-section-title {
    color: #000000;
  }
  .cid-tXzkmH0g2D .mbr-text,
  .cid-tXzkmH0g2D .mbr-section-btn {
    color: #000000;
    text-align: center;
  }
  .cid-tXzkmH0g2D .item-title {
    color: #000000;
  }
  .cid-tXzkmH0g2D .content-head {
    max-width: 800px;
  }
</style>
<section data-bs-version="5.1" class="people03 cid-tXzkmH0g2D" id="team-1-tXzkmH0g2D">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12 content-head">
				<div class="mbr-section-head mb-5">
					<h4 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
						<strong>Наша команда</strong>
					</h4>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="item features-image col-12 col-md-6 col-lg-3">
				<div class="item-wrapper">
					<div class="item-img mb-3">
						<img src="assets/images/photo-1541881856704-3c4b2896c0f8.jpeg" title="">
					</div>
					<div class="item-content align-left">
						<h6 class="item-subtitle mbr-fonts-style mb-3 display-5">
							<strong>Александр</strong></h6>
						<p class="mbr-text mbr-fonts-style mt-3 display-7">Главный разработчик</p>
					</div>
				</div>
			</div>
			<div class="item features-image col-12 col-md-6 col-lg-3">
				<div class="item-wrapper">
					<div class="item-img mb-3">
						<img src="assets/images/photo-1510274642460-65a8de5e52fd.jpeg" title="">
					</div>
					<div class="item-content align-left">
						<h6 class="item-subtitle mbr-fonts-style mb-3 display-5">
							<strong>Екатерина</strong></h6>
						<p class="mbr-text mbr-fonts-style mt-3 display-7">Дизайнер</p>
					</div>
				</div>
			</div>
			<div class="item features-image col-12 col-md-6 col-lg-3">
				<div class="item-wrapper">
					<div class="item-img mb-3">
						<img src="assets/images/photo-1599566150163-29194dcaad36.jpeg" title="">
					</div>
					<div class="item-content align-left">
						<h6 class="item-subtitle mbr-fonts-style mb-3 display-5">
							<strong>Дмитрий</strong></h6>
						<p class="mbr-text mbr-fonts-style mt-3 display-7">Менеджер по продажам</p>
					</div>
				</div>
			</div>
      <div class="item features-image col-12 col-md-6 col-lg-3">
        <div class="item-wrapper">
          <div class="item-img mb-3">
            <img src="assets/images/photo-1676385901160-31e1b9e1c0c7.jpeg" title="">
          </div>
          <div class="item-content align-left">
            <h6 class="item-subtitle mbr-fonts-style mb-3 display-5">
              <strong>Ольга</strong>
            </h6>
            <p class="mbr-text mbr-fonts-style mt-3 display-7">Технический писатель</p>
          </div>
        </div>
      </div>
		</div>
	</div>
</section>
    <style>
  .cid-tXzkmH1b4m {
    padding-top: 5rem;
    padding-bottom: 4rem;
    background-color: transparent;
  }

  .cid-tXzkmH1b4m .item-mb {
    margin-bottom: 2rem;
  }

  @media (max-width: 767px) {
    .cid-tXzkmH1b4m .item-mb {
      margin-bottom: 1rem;
    }
  }

  .cid-tXzkmH1b4m .item-head {
    background: var(--primary-color, #9fe870);
    padding: 2.25rem;
  }

  @media (min-width: 992px) and (max-width: 1200px) {
    .cid-tXzkmH1b4m .item-head {
      padding: 2rem 1.5rem;
      margin-bottom: 2rem;
    }
  }

  @media (max-width: 767px) {
    .cid-tXzkmH1b4m .item-head {
      padding: 2rem 1.5rem;
      margin-bottom: 2rem;
    }
  }

  .cid-tXzkmH1b4m .item-content {
    padding: 2.25rem 2.25rem 0;
    background: #ffffff;
  }

  @media (min-width: 992px) and (max-width: 1200px) {
    .cid-tXzkmH1b4m .item-content {
      padding: 0rem 1.5rem;
    }
  }

  @media (max-width: 767px) {
    .cid-tXzkmH1b4m .item-content {
      padding: 0rem 1.5rem;
    }
  }

  .cid-tXzkmH1b4m .item-wrapper {
    border-radius: 2rem;
    overflow: hidden;
    margin-bottom: 2rem;
    background: #ffffff;
    padding: 0rem;
    height: 100%;
    display: flex;
    flex-flow: column nowrap;
  }

  @media (max-width: 767px) {
    .cid-tXzkmH1b4m .item-wrapper {
      margin-bottom: 1rem;
    }
  }

  @media (min-width: 992px) and (max-width: 1200px) {
    .cid-tXzkmH1b4m .item-wrapper .item-footer {
      padding: 0 1.5rem 2rem;
    }
  }

  @media (min-width: 1201px) {
    .cid-tXzkmH1b4m .item-wrapper .item-footer {
      padding: 0 2rem 2rem;
    }
  }

  .cid-tXzkmH1b4m .btn {
    width: -webkit-fill-available;
  }

  .cid-tXzkmH1b4m .item:focus,
  .cid-tXzkmH1b4m span:focus {
    outline: none;
  }

  .cid-tXzkmH1b4m .mbr-section-btn {
    margin-top: auto !important;
    padding: 2rem 2rem 0;
  }

  @media (max-width: 991px) {
    .cid-tXzkmH1b4m .mbr-section-btn {
      padding: 0rem 2.25rem 2rem;
    }
  }

  @media (max-width: 767px) {
    .cid-tXzkmH1b4m .mbr-section-btn {
      padding: 0rem 1.5rem;
      margin-bottom: 2rem;
    }
  }

  .cid-tXzkmH1b4m .mbr-section-title {
    color: #000000;
  }

  .cid-tXzkmH1b4m .mbr-section-subtitle {
    color: #ffffff;
  }

  .cid-tXzkmH1b4m .mbr-text,
  .cid-tXzkmH1b4m .mbr-section-btn {
    text-align: left;
  }

  .cid-tXzkmH1b4m .item-title {
    text-align: left;
    color: var(--primary-text, #ffffff);
  }

  .cid-tXzkmH1b4m .item-subtitle {
    text-align: left;
    color: var(--primary-text, #ffffff);
  }

  .cid-tXzkmH1b4m .content-head {
    max-width: 800px;
  }
</style>

    <style>
  .cid-tXzkmH1xQU {
    padding-top: 6rem;
    padding-bottom: 6rem;
    background-image: url("assets/images/photo-1470583190240-bd6bbde8a569.jpeg");
  }
  .cid-tXzkmH1xQU .mbr-fallback-image.disabled {
    display: none;
  }
  .cid-tXzkmH1xQU .mbr-fallback-image {
    display: block;
    background-size: cover;
    background-position: center center;
    width: 100%;
    height: 100%;
    position: absolute;
    top: 0;
  }
  .cid-tXzkmH1xQU .card-wrapper {
    background: var(--primary-color, #33333);
    border-radius: 4px;
  }
  @media (max-width: 767px) {
    .cid-tXzkmH1xQU .card-wrapper {
      padding: 2rem 1.5rem;
      margin-bottom: 1rem;
    }
  }
  @media (min-width: 768px) and (max-width: 991px) {
    .cid-tXzkmH1xQU .card-wrapper {
      padding: 2.25rem;
    }
  }
  @media (min-width: 992px) {
    .cid-tXzkmH1xQU .card-wrapper {
      padding: 4rem;
    }
  }
  .cid-tXzkmH1xQU .mbr-text,
  .cid-tXzkmH1xQU .mbr-section-btn {
    text-align: left;
  }
  .cid-tXzkmH1xQU .card-title {
    text-align: left;
    color: var(--primary-text, #ffd7ef);
  }
</style>

    <style>
.cid-tXzkmH1rfo {
  padding-top: 6rem;
  padding-bottom: 6rem;
  background-color: #ffffff;
}
.cid-tXzkmH1rfo .social-row {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-wrap: wrap;
}
.cid-tXzkmH1rfo .social-row .soc-item {
  margin: 8px;
}
.cid-tXzkmH1rfo .social-row .soc-item a:hover .mbr-iconfont,
.cid-tXzkmH1rfo .social-row .soc-item a:focus .mbr-iconfont {
  background-color: #f7f7f7;
}
.cid-tXzkmH1rfo .social-row .soc-item a .mbr-iconfont {
  width: 72px;
  height: 72px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 100%;
  font-size: 32px;
  background-color: #f7f7f7;
  color: var(--primary-color, #393193);
  transition: all 0.3s ease-in-out;
}
.cid-tXzkmH1rfo .row-links {
  width: 100%;
  justify-content: center;
}
.cid-tXzkmH1rfo .mbr-section-title {
  color: #ffffff;
}
.cid-tXzkmH1rfo .mbr-section-title,
.cid-tXzkmH1rfo .social-list {
  color: #000000;
}

</style>
<section data-bs-version="5.1" class="social05 cid-tXzkmH1rfo" id="follow-us-2-tXzkmH1rfo">
    <div class="container">
        <div class="row">
            <h3 class="mbr-section-title align-center mb-5 mbr-fonts-style display-2">
                <strong>Подписывайтесь на нас</strong>
            </h3>
            <div class="col-12">
                <div class="social-row">
                    <div class="soc-item">
                        <a href="#" target="_blank">
                            <span class="mbr-iconfont socicon socicon-facebook"></span>
                        </a>
                    </div>
                    <div class="soc-item">
                        <a href="#" target="_blank">
                            <span class="mbr-iconfont socicon-twitter socicon"></span>
                        </a>
                    </div>
                    <div class="soc-item">
                        <a href="#" target="_blank">
                            <span class="mbr-iconfont socicon-instagram socicon"></span>
                        </a>
                    </div>
                    <div class="soc-item">
                        <a href="#" target="_blank">
                            <span class="mbr-iconfont socicon socicon-linkedin"></span>
                        </a>
                    </div>
                    <div class="soc-item">
                        <a href="#" target="_blank">
                            <span class="mbr-iconfont socicon socicon-twitch"></span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
    <style>
  .cid-tXzkmH1DAz {
    padding-top: 6rem;
    padding-bottom: 6rem;
    background-color: #ffffff;
  }
  .cid-tXzkmH1DAz .item-subtitle {
    line-height: 1.2;
    color: #000000;
  }
  .cid-tXzkmH1DAz img,
  .cid-tXzkmH1DAz .item-img {
    width: 100%;
  }
  .cid-tXzkmH1DAz .item:focus,
  .cid-tXzkmH1DAz span:focus {
    outline: none;
  }
  .cid-tXzkmH1DAz .item {
    margin-bottom: 2rem;
  }
  @media (max-width: 767px) {
    .cid-tXzkmH1DAz .item {
      margin-bottom: 1rem;
    }
  }
  .cid-tXzkmH1DAz .item-wrapper {
    position: relative;
    border-radius: 4px;
    height: 100%;
    display: flex;
    flex-flow: column nowrap;
  }
  .cid-tXzkmH1DAz .mbr-section-title {
    color: #232323;
  }
  .cid-tXzkmH1DAz .mbr-text,
  .cid-tXzkmH1DAz .mbr-section-btn {
    color: #232323;
  }
  .cid-tXzkmH1DAz .item-title {
    color: #232323;
    text-align: center;
  }
  .cid-tXzkmH1DAz .content-head {
    max-width: 800px;
  }
</style>
<section data-bs-version="5.1" class="features03 cid-tXzkmH1DAz" id="clients-1-tXzkmH1DAz">
    <div class="container-fluid">
        <div class="row justify-content-center mb-5">
            <div class="col-12 content-head">
                <div class="mbr-section-head">
                    <h4 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                        <strong>Наши клиенты</strong>
                    </h4>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="item features-image col-12 col-md-6 col-sm-6 col-lg-2 active">
                <div class="item-wrapper">
                    <div class="item-img mb-3">
                        <img src="assets/images/short2.png" title="" data-slide-to="1" data-bs-slide-to="1">
                    </div>
                </div>
            </div>
            <div class="item features-image col-12 col-md-6 col-sm-6 col-lg-2">
                <div class="item-wrapper">
                    <div class="item-img mb-3">
                        <img src="assets/images/short6.png" title="" data-slide-to="2" data-bs-slide-to="2">
                    </div>
                </div>
            </div>
            <div class="item features-image col-12 col-md-6 col-sm-6 col-lg-2">
                <div class="item-wrapper">
                    <div class="item-img mb-3">
                        <img src="assets/images/short5.png" title="" data-slide-to="3" data-bs-slide-to="3">
                    </div>
                </div>
            </div>
            <div class="item features-image col-12 col-md-6 col-sm-6 col-lg-2">
                <div class="item-wrapper">
                    <div class="item-img mb-3">
                        <img src="assets/images/short3.png" title="" data-slide-to="4" data-bs-slide-to="4">
                    </div>
                </div>
            </div>
            <div class="item features-image col-12 col-md-6 col-sm-6 col-lg-2">
                <div class="item-wrapper">
                    <div class="item-img mb-3">
                        <img src="assets/images/short1.png" title="" data-slide-to="5" data-bs-slide-to="5">
                    </div>
                </div>
            </div>
            <div class="item features-image col-12 col-md-6 col-sm-6 col-lg-2">
                <div class="item-wrapper">
                    <div class="item-img mb-3">
                        <img src="assets/images/short4.png" title="" data-slide-to="6" data-bs-slide-to="6">
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
    <style>
.cid-tXzkmH1lzW {
  padding-top: 6rem;
  padding-bottom: 6rem;
  background-color: transparent;
}
.cid-tXzkmH1lzW .mbr-overlay {
  background-color: #ffffff;
  opacity: 0.4;
}
.cid-tXzkmH1lzW form .mbr-section-btn {
  text-align: center;
  width: 100%;
}
.cid-tXzkmH1lzW form .mbr-section-btn .btn {
  display: inline-flex;
}
@media (max-width: 991px) {
  .cid-tXzkmH1lzW form .mbr-section-btn .btn {
    width: 100%;
  }
}
.cid-tXzkmH1lzW .content-head {
  max-width: 800px;
}

</style>
<section data-bs-version="5.1" class="form5 cid-tXzkmH1lzW" id="contact-form-2-tXzkmH1lzW">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 content-head">
                <div class="mbr-section-head mb-5">
                    <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                        <strong>Свяжитесь с нами</strong>
                    </h3>
                </div>
            </div>
        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-lg-8 mx-auto mbr-form" data-form-type="formoid">
                <form action="https://mobirise.eu/" method="POST" class="mbr-form form-with-styler" data-form-title="Form Name"><input type="hidden" name="email" data-form-email="true" value="">
                    <div class="row">
                        <div hidden="hidden" data-form-alert="" class="alert alert-success col-12">Thanks for filling out the form!</div>
                        <div hidden="hidden" data-form-alert-danger="" class="alert alert-danger col-12">
                            Oops...! some problem!
                        </div>
                    </div>
                    <div class="dragArea row">
                        <div class="col-md col-sm-12 form-group mb-3" data-for="name">
                            <input type="text" name="name" placeholder="Имя" data-form-field="name" class="form-control" value="" id="name-form02-0">
                        </div>
                        <div class="col-md col-sm-12 form-group mb-3" data-for="email">
                            <input type="email" name="email" placeholder="Email" data-form-field="email" class="form-control" value="" id="email-form02-0">
                        </div>
                        <div class="col-12 form-group mb-3" data-for="textarea">
                            <textarea name="textarea" placeholder="Сообщение" data-form-field="textarea" class="form-control" id="textarea-form02-0"></textarea>
                        </div>
                        <div class="col-lg-12 col-md-12 col-sm-12 align-center mbr-section-btn"><button type="submit" class="btn btn-primary display-7">Отправить</button></div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>
    <style>
.cid-tXzkmH14Pa {
  padding-top: 6rem;
  padding-bottom: 6rem;
  background-color: transparent;
}
.cid-tXzkmH14Pa .mbr-fallback-image.disabled {
  display: none;
}
.cid-tXzkmH14Pa .mbr-fallback-image {
  display: block;
  background-size: cover;
  background-position: center center;
  width: 100%;
  height: 100%;
  position: absolute;
  top: 0;
}
.cid-tXzkmH14Pa .row {
  justify-content: center;
}
.cid-tXzkmH14Pa .item {
  margin-bottom: 2rem;
}
@media (max-width: 767px) {
  .cid-tXzkmH14Pa .item {
    margin-bottom: 1rem;
  }
}
.cid-tXzkmH14Pa .item .item-wrapper {
  display: flex;
  flex-direction: column;
  height: 100%;
  background: #ffffff;
  padding: 2.25rem;
}
@media (min-width: 992px) and (max-width: 1200px) {
  .cid-tXzkmH14Pa .item .item-wrapper {
    padding: 2rem 1.5rem;
  }
}
@media (max-width: 767px) {
  .cid-tXzkmH14Pa .item .item-wrapper {
    padding: 2rem 1.5rem;
  }
}
.cid-tXzkmH14Pa .content-head {
  max-width: 800px;
}

</style>
<section data-bs-version="5.1" class="contacts01 cid-tXzkmH14Pa" id="contacts-1-tXzkmH14Pa">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 content-head">
                <div class="mbr-section-head mb-5">
                    <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                        <strong>Контакты</strong>
                    </h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="item features-without-image col-12 col-md-6 active">
                <div class="item-wrapper">
                    <div class="text-wrapper">
                        <h6 class="card-title mbr-fonts-style mb-3 display-5">
                            <strong>Телефон</strong>
                        </h6>
                        <p class="mbr-text mbr-fonts-style display-7">
                            <a href="tel:+1-999-123-45-67" class="text-black">+7-999-123-45-67</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="item features-without-image col-12 col-md-6">
                <div class="item-wrapper">
                    <div class="text-wrapper">
                        <h6 class="card-title mbr-fonts-style mb-3 display-5">
                            <strong>Email</strong>
                        </h6>
                        <p class="mbr-text mbr-fonts-style display-7">
                            <a href="mailto:katj0410@gmail.com" class="text-black">info@bugtraker.com</a>
                        </p>
                    </div>
                </div>
            </div>
            <div class="item features-without-image col-12 col-md-6">
                <div class="item-wrapper">
                    <div class="text-wrapper">
                        <h6 class="card-title mbr-fonts-style mb-3 display-5">
                            <strong>Адрес</strong>
                        </h6>
                        <p class="mbr-text mbr-fonts-style display-7">
                            Amsterdam Netherlands
                        </p>
                    </div>
                </div>
            </div>
            <div class="item features-without-image col-12 col-md-6">
                <div class="item-wrapper">
                    <div class="text-wrapper">
                        <h6 class="card-title mbr-fonts-style mb-3 display-5">
                            <strong>Время работы</strong>
                        </h6>
                        <p class="mbr-text mbr-fonts-style display-7">
                            Пн-Пт: 9:00 - 18:00
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
    <style>
.cid-tXzkmH1blP {
  padding-top: 6rem;
  padding-bottom: 6rem;
  background-color: #000000;
}
.cid-tXzkmH1blP .social-row {
  display: flex;
  justify-content: center;
  align-items: center;
  flex-wrap: wrap;
}
.cid-tXzkmH1blP .social-row .soc-item {
  margin: 8px;
}
.cid-tXzkmH1blP .social-row .soc-item a:hover .mbr-iconfont,
.cid-tXzkmH1blP .social-row .soc-item a:focus .mbr-iconfont {
  background-color: #ffffff;
}
.cid-tXzkmH1blP .social-row .soc-item a .mbr-iconfont {
  width: 72px;
  height: 72px;
  display: flex;
  align-items: center;
  justify-content: center;
  border-radius: 100%;
  font-size: 32px;
  background-color: #edefeb;
  color: #000000;
  transition: all 0.3s ease-in-out;
}
.cid-tXzkmH1blP .row-links {
  width: 100%;
  justify-content: center;
}
.cid-tXzkmH1blP .header-menu {
  list-style: none;
  display: flex;
  justify-content: center;
  flex-wrap: wrap;
  padding: 0;
  margin-bottom: 0;
}
.cid-tXzkmH1blP .header-menu li {
  padding: 0 1rem 1rem 1rem;
}
.cid-tXzkmH1blP .header-menu li p {
  margin: 0;
}
.cid-tXzkmH1blP .copyright {
  margin-bottom: 0;
  color: #ffffff;
  text-align: center;
}
.cid-tXzkmH1blP .mbr-section-title {
  color: #ffffff;
}

</style>
<section data-bs-version="5.1" class="footer3 cid-tXzkmH1blP" once="footers" id="footer-3-tXzkmH1blP">
    <div class="container">
        <div class="row">


            <div class="col-12 mt-4">
                <div class="social-row">
                    <div class="soc-item">
                        <a href="#" target="_blank">
                            <span class="mbr-iconfont socicon socicon-facebook display-7"></span>
                        </a>
                    </div>
                    <div class="soc-item">
                        <a href="#" target="_blank">
                            <span class="mbr-iconfont socicon-twitter socicon"></span>
                        </a>
                    </div>
                    <div class="soc-item">
                        <a href="#" target="_blank">
                            <span class="mbr-iconfont socicon-instagram socicon"></span>
                        </a>
                    </div>
                    <div class="soc-item">
                        <a href="#" target="_blank">
                            <span class="mbr-iconfont socicon socicon-linkedin"></span>
                        </a>
                    </div>
                    <div class="soc-item">
                        <a href="#" target="_blank">
                            <span class="mbr-iconfont socicon socicon-twitch"></span>
                        </a>
                    </div>
                </div>
            </div>

            <div class="col-12 mt-5">
                <p class="mbr-fonts-style copyright display-7">
                    © 2023 BUGTRAKER. Все права защищены.
                </p>
            </div>
        </div>
    </div>
</section>

<script src="assets/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="assets/dropdown/js/navbar-dropdown.js"></script>
  <script src="assets/embla/embla.min.js"></script>
  <script src="assets/embla/script.js"></script>
  <script src="assets/smoothscroll/smooth-scroll.js"></script>
  <script src="assets/ytplayer/index.js"></script>
  <script src="assets/theme/js/script.js"></script>
  <script src="assets/formoid/formoid.min.js"></script>

  <script>

    (function(){
      var animationInput = document.createElement('input');
      animationInput.setAttribute('name', 'animation');
      animationInput.setAttribute('type', 'hidden');
      document.body.append(animationInput);
    })();

  </script>
</body>
</html>